# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiCrsszchCUFgaIbnMMiqVT1TzReKH_E
"""

!pip -q install xgboost shap lime imbalanced-learn

import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
from google.colab import files
from sklearn.model_selection import train_test_split

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

uploaded = files.upload() # Select creditcard.csv from your computer
data_file = next(iter(uploaded))
df = pd.read_csv(data_file)

print(f"Loaded file: {data_file}")
print("Dataset shape:", df.shape)
display(df.head())

print("\nColumn names:")
print(df.columns.tolist())

print("\nMissing values per column (top 10):")
display(df.isnull().sum().sort_values(ascending=False).head(10))

print("\nDuplicate rows:", df.duplicated().sum())

class_counts = df["Class"].value_counts().sort_index()
class_percent = (class_counts / len(df) * 100).round(4)
class_summary = pd.DataFrame({
 "count": class_counts.values,
 "percentage": class_percent.values
}, index=["Legitimate (0)", "Fraud (1)"])

print("\nClass distribution:")
display(class_summary)

plt.figure(figsize=(5, 4))
plt.bar(["Legitimate", "Fraud"], class_counts.values)
plt.yscale("log")
plt.title("Class distribution (log scale)")
plt.ylabel("Number of transactions")
plt.show()

rows_before = len(df)
df = df.drop_duplicates().reset_index(drop=True)
rows_after = len(df)

print(f"\nRows before duplicate removal: {rows_before}")
print(f"Rows after duplicate removal : {rows_after}")
print(f"Removed duplicates : {rows_before - rows_after}")

# Log-transform Amount to reduce skewness
df["LogAmount"] = np.log1p(df["Amount"])

# Keep the target separately
X = df.drop(columns=["Class", "Amount"])
y = df["Class"].astype(int)

# These are the only columns we plan to scale later inside CV pipelines
scale_cols_later = ["Time", "LogAmount"]
print("\nFeature matrix shape:", X.shape)
print("Target vector shape :", y.shape)
print("Columns to scale later:", scale_cols_later)

X_dev, X_test, y_dev, y_test = train_test_split(
 X, y, test_size=0.20, stratify=y, random_state=RANDOM_STATE
)

print("Development set shapes:", X_dev.shape, y_dev.shape)
print("Final test set shapes :", X_test.shape, y_test.shape)

def show_ratio(y_split, split_name):
 counts = y_split.value_counts().sort_index()
 pct = (counts / len(y_split) * 100).round(4)
 out = pd.DataFrame(
 {"count": counts.values, "percentage": pct.values},
 index=["Legitimate (0)", "Fraud (1)"]
 )
 print(f"\n{split_name}")
 display(out)

show_ratio(y, "Full dataset")
show_ratio(y_dev, "Development set")
show_ratio(y_test, "Final test set")

neg = (y_dev == 0).sum()
pos = (y_dev == 1).sum()
scale_pos_weight = neg / pos

print(f"\nSuggested XGBoost scale_pos_weight: {scale_pos_weight:.2f}")
print("Step 1 complete.")

"""***Step 2: leakage-safe baseline model pipelines using Weighted Logistic Regression, Random Forest, and XGBoost with AUPRC, Recall, Precision, F1, ROC-AUC, MCC, PR curve, and confusion matrix.***"""

# ============================================================
# STEP 2: Leakage-safe baseline model pipelines
# Title context:
# Explainable Credit Card Fraud Detection:
# A Hybrid Ensemble Approach using SHAP and LIME
#
# This code assumes Step 1 already created these variables:
# X_dev, X_test, y_dev, y_test, scale_cols_later,
# scale_pos_weight, RANDOM_STATE
# ============================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import display

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    average_precision_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_recall_curve,
)

from xgboost import XGBClassifier

# ---------------------------
# 1) Safety checks
# ---------------------------
required_vars = [
    "X_dev", "X_test", "y_dev", "y_test",
    "scale_cols_later", "scale_pos_weight", "RANDOM_STATE"
]
missing_vars = [v for v in required_vars if v not in globals()]
if missing_vars:
    raise ValueError(
        f"Run Step 1 first. Missing variables: {missing_vars}"
    )

# Make sure y is a clean pandas Series
y_dev = pd.Series(y_dev).astype(int).reset_index(drop=True)
y_test = pd.Series(y_test).astype(int).reset_index(drop=True)

# Make sure X is a DataFrame
if not isinstance(X_dev, pd.DataFrame):
    raise TypeError("X_dev must be a pandas DataFrame from Step 1.")
if not isinstance(X_test, pd.DataFrame):
    raise TypeError("X_test must be a pandas DataFrame from Step 1.")

# ---------------------------
# 2) Leakage-safe preprocessing
#    Only Time and LogAmount are scaled
#    and scaling happens INSIDE the pipeline
# ---------------------------
scale_cols = list(scale_cols_later)
other_cols = [c for c in X_dev.columns if c not in scale_cols]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "scale_selected",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler())
            ]),
            scale_cols
        ),
        (
            "keep_rest",
            "passthrough",
            other_cols
        )
    ],
    remainder="drop",
    verbose_feature_names_out=False
)

# ---------------------------
# 3) Baseline models
# ---------------------------
models = {
    "Weighted Logistic Regression": LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        solver="liblinear",
        random_state=RANDOM_STATE
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        class_weight="balanced_subsample",
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),
    "XGBoost": XGBClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="binary:logistic",
        eval_metric="logloss",
        tree_method="hist",
        scale_pos_weight=float(scale_pos_weight),
        random_state=RANDOM_STATE,
        n_jobs=-1,
        verbosity=0
    )
}

# ---------------------------
# 4) CV setup
# ---------------------------
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

def build_pipeline(model):
    return Pipeline([
        ("prep", clone(preprocessor)),
        ("model", clone(model))
    ])

def calculate_metrics(y_true, y_prob, threshold=0.50):
    y_pred = (y_prob >= threshold).astype(int)

    metrics = {
        "AUPRC": average_precision_score(y_true, y_prob),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_prob),
        "MCC": matthews_corrcoef(y_true, y_pred)
    }
    return metrics, y_pred

# ---------------------------
# 5) Out-of-fold CV on DEVELOPMENT set
#    This keeps the workflow leakage-safe
# ---------------------------
oof_probabilities = {}
fitted_baseline_models = {}
cv_rows = []

print("Running Step 2 baseline models on DEVELOPMENT data only...")
print("All model comparison below is based on stratified CV.")
print("The final test set is only used later in the optional locked snapshot.\n")

for model_name, model in models.items():
    print(f"Model: {model_name}")
    oof_prob = np.zeros(len(y_dev), dtype=float)

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X_dev, y_dev), start=1):
        X_train = X_dev.iloc[train_idx].copy()
        X_valid = X_dev.iloc[valid_idx].copy()
        y_train = y_dev.iloc[train_idx].copy()

        pipe = build_pipeline(model)
        pipe.fit(X_train, y_train)

        fold_prob = pipe.predict_proba(X_valid)[:, 1]
        oof_prob[valid_idx] = fold_prob

        print(f"  Fold {fold}/5 done")

    oof_probabilities[model_name] = oof_prob

    model_metrics, _ = calculate_metrics(y_dev, oof_prob, threshold=0.50)
    model_metrics["Model"] = model_name
    cv_rows.append(model_metrics)

    # Fit once on full development data for later steps / optional test snapshot
    final_pipe = build_pipeline(model)
    final_pipe.fit(X_dev, y_dev)
    fitted_baseline_models[model_name] = final_pipe

    print("  Full development fit done\n")

# ---------------------------
# 6) CV results table
# ---------------------------
results_df = pd.DataFrame(cv_rows)[
    ["Model", "AUPRC", "Recall", "Precision", "F1", "ROC-AUC", "MCC"]
].sort_values(by="AUPRC", ascending=False).reset_index(drop=True)

print("\nBaseline CV Results (sorted by AUPRC):")
display(results_df.round(6))

results_df.to_csv("step2_baseline_cv_results.csv", index=False)
print("Saved: step2_baseline_cv_results.csv")

best_model_name = results_df.iloc[0]["Model"]
best_oof_prob = oof_probabilities[best_model_name]
_, best_oof_pred = calculate_metrics(y_dev, best_oof_prob, threshold=0.50)

print(f"\nBest baseline by AUPRC on development CV: {best_model_name}")

# ---------------------------
# 7) Precision-Recall curves
# ---------------------------
plt.figure(figsize=(8, 6))

for model_name, probs in oof_probabilities.items():
    precision_vals, recall_vals, _ = precision_recall_curve(y_dev, probs)
    auprc_val = average_precision_score(y_dev, probs)
    plt.plot(recall_vals, precision_vals, label=f"{model_name} (AUPRC={auprc_val:.4f})")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curves (Out-of-Fold Development Predictions)")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# ---------------------------
# 8) Confusion matrix of best baseline
#    based on OOF development predictions
# ---------------------------
cm = confusion_matrix(y_dev, best_oof_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title(f"Confusion Matrix - {best_model_name} (threshold=0.50)")
plt.show()

# ---------------------------
# 9) Optional locked final-test snapshot
#    IMPORTANT:
#    This is okay for a baseline snapshot,
#    but do NOT use it to tune hyperparameters.
#    If you want the strictest protocol, set this to False.
# ---------------------------
RUN_FINAL_TEST_SNAPSHOT = True

if RUN_FINAL_TEST_SNAPSHOT:
    test_rows = []

    for model_name, fitted_model in fitted_baseline_models.items():
        test_prob = fitted_model.predict_proba(X_test)[:, 1]
        test_metrics, _ = calculate_metrics(y_test, test_prob, threshold=0.50)
        test_metrics["Model"] = model_name
        test_rows.append(test_metrics)

    test_results_df = pd.DataFrame(test_rows)[
        ["Model", "AUPRC", "Recall", "Precision", "F1", "ROC-AUC", "MCC"]
    ].sort_values(by="AUPRC", ascending=False).reset_index(drop=True)

    print("\nLocked Final-Test Baseline Snapshot:")
    display(test_results_df.round(6))

    test_results_df.to_csv("step2_baseline_final_test_snapshot.csv", index=False)
    print("Saved: step2_baseline_final_test_snapshot.csv")

print("\nStep 2 complete.")

"""***STEP 3: Proposed hybrid framework , Isolation Forest anomaly branch + stacking meta-learner***


"""

# ============================================================
# STEP 3: Proposed hybrid framework
# Isolation Forest anomaly branch + stacking meta-learner
#
# IMPORTANT:
# This code assumes Step 1 and Step 2 were already run
# in the same Colab runtime.
# ============================================================

import warnings
warnings.filterwarnings("ignore")

import os
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import display
from sklearn.base import clone
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_recall_curve,
)

# ---------------------------
# 0) Create folders
# ---------------------------
os.makedirs("results", exist_ok=True)
os.makedirs("figures", exist_ok=True)
os.makedirs("models", exist_ok=True)

# ---------------------------
# 1) Safety checks
# ---------------------------
required_vars = [
    "X_dev", "X_test", "y_dev", "y_test",
    "RANDOM_STATE", "preprocessor", "cv",
    "oof_probabilities", "fitted_baseline_models"
]
missing_vars = [v for v in required_vars if v not in globals()]
if missing_vars:
    raise ValueError(
        f"Run Step 1 and Step 2 first. Missing variables: {missing_vars}"
    )

# Clean indexing
X_dev = X_dev.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_dev = pd.Series(y_dev).astype(int).reset_index(drop=True)
y_test = pd.Series(y_test).astype(int).reset_index(drop=True)

# Step 2 used these three supervised models
BASE_MODEL_NAMES = [
    "Weighted Logistic Regression",
    "Random Forest",
    "XGBoost"
]

for model_name in BASE_MODEL_NAMES:
    if model_name not in oof_probabilities:
        raise ValueError(f"Missing OOF probabilities for: {model_name}")
    if model_name not in fitted_baseline_models:
        raise ValueError(f"Missing fitted Step 2 model for: {model_name}")

# ---------------------------
# 2) Helper functions
# ---------------------------
def calculate_metrics(y_true, y_score, threshold=0.50):
    y_true = np.asarray(y_true)
    y_score = np.asarray(y_score)
    y_pred = (y_score >= threshold).astype(int)

    metrics = {
        "AUPRC": average_precision_score(y_true, y_score),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_score),
        "MCC": matthews_corrcoef(y_true, y_pred)
    }
    return metrics, y_pred


def build_iforest_pipeline(contamination_value):
    contamination_value = float(max(contamination_value, 1e-4))

    return Pipeline([
        ("prep", clone(preprocessor)),
        ("model", IsolationForest(
            n_estimators=300,
            contamination=contamination_value,
            random_state=RANDOM_STATE,
            n_jobs=-1
        ))
    ])


def anomaly_score_from_pipeline(pipe, X):
    # IsolationForest.decision_function:
    # higher value = more normal
    # lower value = more abnormal
    # We flip the sign so that:
    # higher score = more suspicious / more anomalous
    return -pipe.decision_function(X)


def build_meta_learner():
    return Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            class_weight="balanced",
            max_iter=1000,
            solver="liblinear",
            random_state=RANDOM_STATE
        ))
    ])


def get_oof_stack_predictions(X_meta, y_true, cv_object, label):
    oof_prob = np.zeros(len(y_true), dtype=float)

    for fold, (train_idx, valid_idx) in enumerate(cv_object.split(X_meta, y_true), start=1):
        meta_pipe = build_meta_learner()
        meta_pipe.fit(X_meta.iloc[train_idx], y_true.iloc[train_idx])
        oof_prob[valid_idx] = meta_pipe.predict_proba(X_meta.iloc[valid_idx])[:, 1]
        print(f"{label} meta fold {fold}/5 done")

    final_meta_pipe = build_meta_learner()
    final_meta_pipe.fit(X_meta, y_true)

    return oof_prob, final_meta_pipe

# ---------------------------
# 3) Isolation Forest anomaly branch
#    Leakage-safe OOF anomaly scores on development set
# ---------------------------
print("Running Step 3: anomaly-aware hybrid framework...\n")
print("Part A: Building Isolation Forest anomaly branch")

iforest_oof_score = np.zeros(len(y_dev), dtype=float)

for fold, (train_idx, valid_idx) in enumerate(cv.split(X_dev, y_dev), start=1):
    X_train = X_dev.iloc[train_idx].copy()
    X_valid = X_dev.iloc[valid_idx].copy()
    y_train = y_dev.iloc[train_idx].copy()

    fold_contamination = float(y_train.mean())
    iforest_pipe = build_iforest_pipeline(fold_contamination)
    iforest_pipe.fit(X_train)

    iforest_oof_score[valid_idx] = anomaly_score_from_pipeline(iforest_pipe, X_valid)
    print(f"Isolation Forest fold {fold}/5 done")

# Final Isolation Forest fit on full development set for locked test snapshot
final_iforest_pipe = build_iforest_pipeline(float(y_dev.mean()))
final_iforest_pipe.fit(X_dev)
iforest_test_score = anomaly_score_from_pipeline(final_iforest_pipe, X_test)

print("\nIsolation Forest anomaly branch complete.\n")

# ---------------------------
# 4) Build meta-features
#    Use Step 2 OOF probabilities + anomaly score
# ---------------------------
print("Part B: Building meta-features")

meta_dev_supervised = pd.DataFrame({
    "lr_prob": np.asarray(oof_probabilities["Weighted Logistic Regression"]),
    "rf_prob": np.asarray(oof_probabilities["Random Forest"]),
    "xgb_prob": np.asarray(oof_probabilities["XGBoost"])
}).reset_index(drop=True)

meta_test_supervised = pd.DataFrame({
    "lr_prob": fitted_baseline_models["Weighted Logistic Regression"].predict_proba(X_test)[:, 1],
    "rf_prob": fitted_baseline_models["Random Forest"].predict_proba(X_test)[:, 1],
    "xgb_prob": fitted_baseline_models["XGBoost"].predict_proba(X_test)[:, 1]
}).reset_index(drop=True)

meta_dev_hybrid = meta_dev_supervised.copy()
meta_dev_hybrid["iforest_anomaly_score"] = iforest_oof_score

meta_test_hybrid = meta_test_supervised.copy()
meta_test_hybrid["iforest_anomaly_score"] = iforest_test_score

display(meta_dev_hybrid.head())

# ---------------------------
# 5) Standard ensemble baseline:
#    Soft voting over the three supervised models
# ---------------------------
soft_vote_dev_prob = meta_dev_supervised.mean(axis=1).to_numpy()
soft_vote_test_prob = meta_test_supervised.mean(axis=1).to_numpy()

# ---------------------------
# 6) Stacking without anomaly score
#    (ablation / baseline)
# ---------------------------
print("\nPart C: Supervised-only stacking")
stack_supervised_dev_prob, final_stack_supervised = get_oof_stack_predictions(
    meta_dev_supervised,
    y_dev,
    cv,
    label="Supervised stacking"
)
stack_supervised_test_prob = final_stack_supervised.predict_proba(meta_test_supervised)[:, 1]

# ---------------------------
# 7) Hybrid stacking with anomaly score
#    (proposed Step 3 framework)
# ---------------------------
print("\nPart D: Hybrid stacking with Isolation Forest")
stack_hybrid_dev_prob, final_stack_hybrid = get_oof_stack_predictions(
    meta_dev_hybrid,
    y_dev,
    cv,
    label="Hybrid stacking"
)
stack_hybrid_test_prob = final_stack_hybrid.predict_proba(meta_test_hybrid)[:, 1]

# ---------------------------
# 8) Development-set comparison
#    All numbers below use leakage-safe OOF predictions
# ---------------------------
THRESHOLD = 0.50

dev_candidates = {
    "Soft Voting (Supervised)": soft_vote_dev_prob,
    "Supervised Stacking": stack_supervised_dev_prob,
    "Hybrid Stacking + IsolationForest": stack_hybrid_dev_prob
}

dev_rows = []
dev_pred_labels = {}

for model_name, scores in dev_candidates.items():
    metrics, y_pred = calculate_metrics(y_dev, scores, threshold=THRESHOLD)
    metrics["Model"] = model_name
    dev_rows.append(metrics)
    dev_pred_labels[model_name] = y_pred

step3_dev_results_df = pd.DataFrame(dev_rows)[
    ["Model", "AUPRC", "Recall", "Precision", "F1", "ROC-AUC", "MCC"]
].sort_values(by="AUPRC", ascending=False).reset_index(drop=True)

print("\nStep 3 Development Results (OOF, sorted by AUPRC):")
display(step3_dev_results_df.round(6))

step3_dev_results_df.to_csv("results/step3_hybrid_dev_results.csv", index=False)
print("Saved: results/step3_hybrid_dev_results.csv")

best_step3_model_name = step3_dev_results_df.iloc[0]["Model"]
best_step3_dev_scores = dev_candidates[best_step3_model_name]
_, best_step3_dev_pred = calculate_metrics(y_dev, best_step3_dev_scores, threshold=THRESHOLD)

print(f"\nBest Step 3 model on development OOF by AUPRC: {best_step3_model_name}")

# ---------------------------
# 9) PR curve plot
# ---------------------------
plt.figure(figsize=(8, 6))

for model_name, scores in dev_candidates.items():
    precision_vals, recall_vals, _ = precision_recall_curve(y_dev, scores)
    auprc_val = average_precision_score(y_dev, scores)
    plt.plot(recall_vals, precision_vals, label=f"{model_name} (AUPRC={auprc_val:.4f})")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Step 3 Precision-Recall Curves (OOF Development Predictions)")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig("figures/step3_pr_curves.png", dpi=300, bbox_inches="tight")
plt.show()

# ---------------------------
# 10) Confusion matrix of the best Step 3 framework
#     using default threshold = 0.50
# ---------------------------
cm = confusion_matrix(y_dev, best_step3_dev_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title(f"Step 3 Confusion Matrix - {best_step3_model_name} (threshold=0.50)")
plt.savefig("figures/step3_confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()

# ---------------------------
# 11) Locked final-test snapshot
#     For comparison only.
#     Step 4 will do calibration + threshold optimization.
# ---------------------------
test_candidates = {
    "Soft Voting (Supervised)": soft_vote_test_prob,
    "Supervised Stacking": stack_supervised_test_prob,
    "Hybrid Stacking + IsolationForest": stack_hybrid_test_prob
}

test_rows = []

for model_name, scores in test_candidates.items():
    metrics, _ = calculate_metrics(y_test, scores, threshold=THRESHOLD)
    metrics["Model"] = model_name
    test_rows.append(metrics)

step3_test_results_df = pd.DataFrame(test_rows)[
    ["Model", "AUPRC", "Recall", "Precision", "F1", "ROC-AUC", "MCC"]
].sort_values(by="AUPRC", ascending=False).reset_index(drop=True)

print("\nStep 3 Locked Final-Test Snapshot:")
display(step3_test_results_df.round(6))

step3_test_results_df.to_csv("results/step3_hybrid_final_test_snapshot.csv", index=False)
print("Saved: results/step3_hybrid_final_test_snapshot.csv")

# ---------------------------
# 12) Save everything needed for Step 4
# ---------------------------
step3_bundle = {
    "base_model_names": BASE_MODEL_NAMES,

    "meta_dev_supervised": meta_dev_supervised,
    "meta_test_supervised": meta_test_supervised,
    "meta_dev_hybrid": meta_dev_hybrid,
    "meta_test_hybrid": meta_test_hybrid,

    "iforest_oof_score": iforest_oof_score,
    "iforest_test_score": iforest_test_score,

    "soft_vote_dev_prob": soft_vote_dev_prob,
    "soft_vote_test_prob": soft_vote_test_prob,

    "stack_supervised_dev_prob": stack_supervised_dev_prob,
    "stack_supervised_test_prob": stack_supervised_test_prob,

    "hybrid_stack_dev_prob": stack_hybrid_dev_prob,
    "hybrid_stack_test_prob": stack_hybrid_test_prob,

    "final_iforest_pipe": final_iforest_pipe,
    "final_stack_supervised": final_stack_supervised,
    "final_stack_hybrid": final_stack_hybrid,

    "step3_dev_results_df": step3_dev_results_df,
    "step3_test_results_df": step3_test_results_df
}

joblib.dump(step3_bundle, "models/step3_bundle.joblib")
print("Saved: models/step3_bundle.joblib")

print("\nStep 3 complete.")

# ============================================================
# STEP 4: Calibration + threshold optimization
#
# What this step does:
# 1) Takes the probability outputs from Step 3
# 2) Compares Raw vs Platt vs Isotonic calibration
# 3) Selects the best calibration method using development Brier score
# 4) Finds the best operating threshold using F2-score on development data
# 5) Compares default 0.50 vs optimized threshold
# 6) Saves tables, figures, and a bundle for Step 5
#
# IMPORTANT:
# - Run this after Step 3 in the same Colab runtime
# - This code keeps the final test set untouched for model/threshold selection
# ============================================================

import warnings
warnings.filterwarnings("ignore")

import os
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import display
from sklearn.linear_model import LogisticRegression
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.calibration import calibration_curve
from sklearn.metrics import (
    average_precision_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    fbeta_score,
    matthews_corrcoef,
    confusion_matrix,
    ConfusionMatrixDisplay,
    brier_score_loss,
    log_loss,
)

# ---------------------------
# 0) Folders
# ---------------------------
os.makedirs("results", exist_ok=True)
os.makedirs("figures", exist_ok=True)
os.makedirs("models", exist_ok=True)

# ---------------------------
# 1) Safety checks
# ---------------------------
required_vars = ["y_dev", "y_test", "RANDOM_STATE"]
missing_vars = [v for v in required_vars if v not in globals()]
if missing_vars:
    raise ValueError(
        f"Run Step 1 and Step 3 first. Missing variables: {missing_vars}"
    )

if "step3_bundle" not in globals():
    if os.path.exists("models/step3_bundle.joblib"):
        step3_bundle = joblib.load("models/step3_bundle.joblib")
        print("Loaded: models/step3_bundle.joblib")
    else:
        raise ValueError(
            "Could not find Step 3 bundle. Run Step 3 first in this Colab runtime."
        )

# If Step 3 results are not still in memory, recover them from the bundle
if "step3_dev_results_df" not in globals():
    if "step3_dev_results_df" in step3_bundle:
        step3_dev_results_df = step3_bundle["step3_dev_results_df"]
    else:
        raise ValueError("step3_dev_results_df not found. Run Step 3 first.")

if "step3_test_results_df" not in globals():
    if "step3_test_results_df" in step3_bundle:
        step3_test_results_df = step3_bundle["step3_test_results_df"]

# Clean y
y_dev = pd.Series(y_dev).astype(int).reset_index(drop=True)
y_test = pd.Series(y_test).astype(int).reset_index(drop=True)

# ---------------------------
# 2) Step 3 candidate probabilities
# ---------------------------
candidate_probabilities = {
    "Soft Voting (Supervised)": {
        "dev": np.asarray(step3_bundle["soft_vote_dev_prob"], dtype=float),
        "test": np.asarray(step3_bundle["soft_vote_test_prob"], dtype=float)
    },
    "Supervised Stacking": {
        "dev": np.asarray(step3_bundle["stack_supervised_dev_prob"], dtype=float),
        "test": np.asarray(step3_bundle["stack_supervised_test_prob"], dtype=float)
    },
    "Hybrid Stacking + IsolationForest": {
        "dev": np.asarray(step3_bundle["hybrid_stack_dev_prob"], dtype=float),
        "test": np.asarray(step3_bundle["hybrid_stack_test_prob"], dtype=float)
    }
}

# ---------------------------
# 3) Configuration
# ---------------------------
CALIBRATION_METHODS = ["Raw", "Platt", "Isotonic"]
THRESHOLD_SCAN = np.linspace(0.001, 0.999, 999)
CALIBRATION_SPLITS = 5

# Keep model selection consistent with your project plan:
# choose the final model using the best Step 3 development AUPRC,
# then improve that chosen model with calibration + threshold tuning.
MODEL_SELECTION_RULE = "best_step3_dev_auprc"

# ---------------------------
# 4) Helper functions
# ---------------------------
def clip_probs(p):
    p = np.asarray(p, dtype=float)
    return np.clip(p, 1e-6, 1 - 1e-6)

def calculate_metrics(y_true, y_prob, threshold=0.50):
    y_true = np.asarray(y_true, dtype=int)
    y_prob = clip_probs(y_prob)
    y_pred = (y_prob >= threshold).astype(int)

    metrics = {
        "AUPRC": average_precision_score(y_true, y_prob),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "F2": fbeta_score(y_true, y_pred, beta=2, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_prob),
        "MCC": matthews_corrcoef(y_true, y_pred),
        "Brier": brier_score_loss(y_true, y_prob),
        "LogLoss": log_loss(y_true, y_prob, labels=[0, 1]),
        "Predicted Fraud Alerts": int(y_pred.sum())
    }
    return metrics, y_pred

def fit_platt(prob_train, y_train):
    model = LogisticRegression(
        max_iter=1000,
        solver="lbfgs",
        random_state=RANDOM_STATE
    )
    model.fit(np.asarray(prob_train).reshape(-1, 1), np.asarray(y_train))
    return model

def predict_platt(model, prob):
    return model.predict_proba(np.asarray(prob).reshape(-1, 1))[:, 1]

def fit_isotonic(prob_train, y_train):
    model = IsotonicRegression(
        out_of_bounds="clip",
        y_min=0.0,
        y_max=1.0
    )
    model.fit(np.asarray(prob_train), np.asarray(y_train))
    return model

def predict_isotonic(model, prob):
    return model.predict(np.asarray(prob))

def crossfit_calibration(dev_prob, test_prob, y_true, method):
    dev_prob = clip_probs(dev_prob)
    test_prob = clip_probs(test_prob)

    if method == "Raw":
        return {
            "dev_prob": dev_prob,
            "test_prob": test_prob,
            "full_model": None
        }

    calib_cv = StratifiedKFold(
        n_splits=CALIBRATION_SPLITS,
        shuffle=True,
        random_state=RANDOM_STATE
    )

    oof_calibrated = np.zeros(len(y_true), dtype=float)

    for fold, (train_idx, valid_idx) in enumerate(calib_cv.split(dev_prob.reshape(-1, 1), y_true), start=1):
        fold_prob_train = dev_prob[train_idx]
        fold_prob_valid = dev_prob[valid_idx]
        fold_y_train = y_true.iloc[train_idx]

        if method == "Platt":
            fold_model = fit_platt(fold_prob_train, fold_y_train)
            oof_calibrated[valid_idx] = predict_platt(fold_model, fold_prob_valid)

        elif method == "Isotonic":
            fold_model = fit_isotonic(fold_prob_train, fold_y_train)
            oof_calibrated[valid_idx] = predict_isotonic(fold_model, fold_prob_valid)

    # Fit once on full development probabilities for later use on final test
    if method == "Platt":
        full_model = fit_platt(dev_prob, y_true)
        test_calibrated = predict_platt(full_model, test_prob)

    elif method == "Isotonic":
        full_model = fit_isotonic(dev_prob, y_true)
        test_calibrated = predict_isotonic(full_model, test_prob)

    return {
        "dev_prob": clip_probs(oof_calibrated),
        "test_prob": clip_probs(test_calibrated),
        "full_model": full_model
    }

def choose_best_calibration(dev_prob, test_prob, y_true, model_name):
    method_outputs = {}
    method_rows = []

    for method in CALIBRATION_METHODS:
        out = crossfit_calibration(dev_prob, test_prob, y_true, method)
        method_outputs[method] = out

        method_rows.append({
            "Model": model_name,
            "Calibration": method,
            "Dev_Brier": brier_score_loss(y_true, out["dev_prob"]),
            "Dev_LogLoss": log_loss(y_true, out["dev_prob"], labels=[0, 1]),
            "Dev_AUPRC": average_precision_score(y_true, out["dev_prob"]),
            "Dev_ROC-AUC": roc_auc_score(y_true, out["dev_prob"])
        })

    method_df = pd.DataFrame(method_rows).sort_values(
        by=["Dev_Brier", "Dev_LogLoss", "Dev_AUPRC"],
        ascending=[True, True, False]
    ).reset_index(drop=True)

    # Step 4 is explicitly a calibration step.
    # So we keep "Raw" as the no-calibration baseline,
    # but choose the selected calibration only from Platt vs Isotonic.
    selectable_df = method_df[method_df["Calibration"] != "Raw"].copy()
    selectable_df = selectable_df.sort_values(
        by=["Dev_Brier", "Dev_LogLoss", "Dev_AUPRC"],
        ascending=[True, True, False]
    ).reset_index(drop=True)

    chosen_method = selectable_df.iloc[0]["Calibration"]

    return {
        "comparison_df": method_df,
        "chosen_method": chosen_method,
        "chosen_dev_prob": method_outputs[chosen_method]["dev_prob"],
        "chosen_test_prob": method_outputs[chosen_method]["test_prob"],
        "chosen_calibrator": method_outputs[chosen_method]["full_model"],
        "all_method_outputs": method_outputs
    }

def optimize_threshold(y_true, y_prob):
    rows = []

    for threshold in THRESHOLD_SCAN:
        y_pred = (y_prob >= threshold).astype(int)

        rows.append({
            "Threshold": float(threshold),
            "Recall": recall_score(y_true, y_pred, zero_division=0),
            "Precision": precision_score(y_true, y_pred, zero_division=0),
            "F1": f1_score(y_true, y_pred, zero_division=0),
            "F2": fbeta_score(y_true, y_pred, beta=2, zero_division=0),
            "MCC": matthews_corrcoef(y_true, y_pred),
            "Predicted Fraud Alerts": int(y_pred.sum())
        })

    threshold_df = pd.DataFrame(rows)

    # Main criterion: highest F2
    best_f2 = threshold_df["F2"].max()
    best_rows = threshold_df[threshold_df["F2"] == best_f2].copy()

    # Tie-breakers: higher MCC, then higher Precision, then lower threshold
    best_rows = best_rows.sort_values(
        by=["MCC", "Precision", "Threshold"],
        ascending=[False, False, True]
    ).reset_index(drop=True)

    best_threshold = float(best_rows.iloc[0]["Threshold"])

    return best_threshold, threshold_df

def summarize_single_setting(y_true, y_prob, threshold, label):
    metrics, _ = calculate_metrics(y_true, y_prob, threshold=threshold)
    metrics["Setting"] = label
    metrics["Threshold"] = float(threshold)
    return metrics

# ---------------------------
# 5) Step 4 over all Step 3 candidates
# ---------------------------
print("Running Step 4: calibration + threshold optimization...\n")

calibration_comparison_rows = []
step4_dev_rows = []
step4_test_rows = []
per_model_outputs = {}

for model_name, probs in candidate_probabilities.items():
    print(f"Processing: {model_name}")

    raw_dev_prob = clip_probs(probs["dev"])
    raw_test_prob = clip_probs(probs["test"])

    calibration_out = choose_best_calibration(
        dev_prob=raw_dev_prob,
        test_prob=raw_test_prob,
        y_true=y_dev,
        model_name=model_name
    )

    calibration_df = calibration_out["comparison_df"]
    chosen_method = calibration_out["chosen_method"]
    chosen_dev_prob = calibration_out["chosen_dev_prob"]
    chosen_test_prob = calibration_out["chosen_test_prob"]
    chosen_calibrator = calibration_out["chosen_calibrator"]

    calibration_comparison_rows.append(calibration_df)

    best_threshold, threshold_scan_df = optimize_threshold(y_dev, chosen_dev_prob)

    dev_metrics, dev_pred = calculate_metrics(y_dev, chosen_dev_prob, threshold=best_threshold)
    dev_metrics["Model"] = model_name
    dev_metrics["Calibration"] = chosen_method
    dev_metrics["Optimized Threshold"] = best_threshold
    step4_dev_rows.append(dev_metrics)

    test_metrics, test_pred = calculate_metrics(y_test, chosen_test_prob, threshold=best_threshold)
    test_metrics["Model"] = model_name
    test_metrics["Calibration"] = chosen_method
    test_metrics["Optimized Threshold"] = best_threshold
    step4_test_rows.append(test_metrics)

    per_model_outputs[model_name] = {
        "raw_dev_prob": raw_dev_prob,
        "raw_test_prob": raw_test_prob,
        "calibration_df": calibration_df,
        "chosen_method": chosen_method,
        "chosen_dev_prob": chosen_dev_prob,
        "chosen_test_prob": chosen_test_prob,
        "chosen_calibrator": chosen_calibrator,
        "best_threshold": best_threshold,
        "threshold_scan_df": threshold_scan_df,
        "dev_pred_at_best_threshold": dev_pred,
        "test_pred_at_best_threshold": test_pred,
        "all_method_outputs": calibration_out["all_method_outputs"]
    }

    print(f"  Selected calibration: {chosen_method}")
    print(f"  Optimized threshold : {best_threshold:.3f}\n")

calibration_comparison_df = pd.concat(calibration_comparison_rows, ignore_index=True)
step4_dev_results_df = pd.DataFrame(step4_dev_rows)[[
    "Model", "Calibration", "Optimized Threshold",
    "AUPRC", "Recall", "Precision", "F1", "F2", "ROC-AUC", "MCC",
    "Brier", "LogLoss", "Predicted Fraud Alerts"
]].sort_values(by="AUPRC", ascending=False).reset_index(drop=True)

step4_test_results_df = pd.DataFrame(step4_test_rows)[[
    "Model", "Calibration", "Optimized Threshold",
    "AUPRC", "Recall", "Precision", "F1", "F2", "ROC-AUC", "MCC",
    "Brier", "LogLoss", "Predicted Fraud Alerts"
]].sort_values(by="AUPRC", ascending=False).reset_index(drop=True)

print("\nCalibration comparison (development):")
display(calibration_comparison_df.round(6))

print("\nStep 4 development results (selected calibration + optimized threshold):")
display(step4_dev_results_df.round(6))

print("\nStep 4 locked final-test snapshot:")
display(step4_test_results_df.round(6))

calibration_comparison_df.to_csv("results/step4_calibration_comparison.csv", index=False)
step4_dev_results_df.to_csv("results/step4_candidate_dev_results.csv", index=False)
step4_test_results_df.to_csv("results/step4_candidate_test_results.csv", index=False)

print("Saved:")
print("  results/step4_calibration_comparison.csv")
print("  results/step4_candidate_dev_results.csv")
print("  results/step4_candidate_test_results.csv")

# ---------------------------
# 6) Choose the final model for deep-dive analysis
#    Rule: best Step 3 development AUPRC
# ---------------------------
if MODEL_SELECTION_RULE == "best_step3_dev_auprc":
    final_model_name = (
        step3_dev_results_df.sort_values(by="AUPRC", ascending=False).iloc[0]["Model"]
    )
else:
    final_model_name = "Hybrid Stacking + IsolationForest"

final_out = per_model_outputs[final_model_name]
final_calibration = final_out["chosen_method"]
final_threshold = final_out["best_threshold"]

print(f"\nFinal Step 4 model for deep-dive analysis: {final_model_name}")
print(f"Selected calibration method: {final_calibration}")
print(f"Selected optimized threshold: {final_threshold:.3f}")

# ---------------------------
# 7) Detailed ablation for the selected final model
# ---------------------------
selected_model_ablation_dev_rows = []
selected_model_ablation_test_rows = []

# A) raw @ 0.50
selected_model_ablation_dev_rows.append(
    summarize_single_setting(
        y_dev, final_out["raw_dev_prob"], 0.50,
        label="Raw @ 0.50"
    )
)
selected_model_ablation_test_rows.append(
    summarize_single_setting(
        y_test, final_out["raw_test_prob"], 0.50,
        label="Raw @ 0.50"
    )
)

# B) raw @ best raw threshold
best_raw_threshold, raw_threshold_df = optimize_threshold(y_dev, final_out["raw_dev_prob"])
selected_model_ablation_dev_rows.append(
    summarize_single_setting(
        y_dev, final_out["raw_dev_prob"], best_raw_threshold,
        label="Raw @ optimized threshold"
    )
)
selected_model_ablation_test_rows.append(
    summarize_single_setting(
        y_test, final_out["raw_test_prob"], best_raw_threshold,
        label="Raw @ optimized threshold"
    )
)

# C) calibrated @ 0.50
selected_model_ablation_dev_rows.append(
    summarize_single_setting(
        y_dev, final_out["chosen_dev_prob"], 0.50,
        label=f"{final_calibration} @ 0.50"
    )
)
selected_model_ablation_test_rows.append(
    summarize_single_setting(
        y_test, final_out["chosen_test_prob"], 0.50,
        label=f"{final_calibration} @ 0.50"
    )
)

# D) calibrated @ optimized threshold
selected_model_ablation_dev_rows.append(
    summarize_single_setting(
        y_dev, final_out["chosen_dev_prob"], final_threshold,
        label=f"{final_calibration} @ optimized threshold"
    )
)
selected_model_ablation_test_rows.append(
    summarize_single_setting(
        y_test, final_out["chosen_test_prob"], final_threshold,
        label=f"{final_calibration} @ optimized threshold"
    )
)

selected_model_ablation_dev_df = pd.DataFrame(selected_model_ablation_dev_rows)[[
    "Setting", "Threshold",
    "AUPRC", "Recall", "Precision", "F1", "F2", "ROC-AUC", "MCC",
    "Brier", "LogLoss", "Predicted Fraud Alerts"
]]

selected_model_ablation_test_df = pd.DataFrame(selected_model_ablation_test_rows)[[
    "Setting", "Threshold",
    "AUPRC", "Recall", "Precision", "F1", "F2", "ROC-AUC", "MCC",
    "Brier", "LogLoss", "Predicted Fraud Alerts"
]]

print("\nSelected-model ablation on development:")
display(selected_model_ablation_dev_df.round(6))

print("\nSelected-model ablation on final test:")
display(selected_model_ablation_test_df.round(6))

selected_model_ablation_dev_df.to_csv("results/step4_selected_model_ablation_dev.csv", index=False)
selected_model_ablation_test_df.to_csv("results/step4_selected_model_ablation_test.csv", index=False)

# ---------------------------
# 8) Anomaly ablation
#    Compare stacking without anomaly vs with anomaly
# ---------------------------
anomaly_ablation_dev_df = None
anomaly_ablation_test_df = None

if (
    "Supervised Stacking" in per_model_outputs and
    "Hybrid Stacking + IsolationForest" in per_model_outputs
):
    anomaly_dev_rows = []
    anomaly_test_rows = []

    for model_name in ["Supervised Stacking", "Hybrid Stacking + IsolationForest"]:
        model_out = per_model_outputs[model_name]
        dev_metrics, _ = calculate_metrics(
            y_dev,
            model_out["chosen_dev_prob"],
            threshold=model_out["best_threshold"]
        )
        dev_metrics["Model"] = model_name
        dev_metrics["Calibration"] = model_out["chosen_method"]
        dev_metrics["Threshold"] = model_out["best_threshold"]
        anomaly_dev_rows.append(dev_metrics)

        test_metrics, _ = calculate_metrics(
            y_test,
            model_out["chosen_test_prob"],
            threshold=model_out["best_threshold"]
        )
        test_metrics["Model"] = model_name
        test_metrics["Calibration"] = model_out["chosen_method"]
        test_metrics["Threshold"] = model_out["best_threshold"]
        anomaly_test_rows.append(test_metrics)

    anomaly_ablation_dev_df = pd.DataFrame(anomaly_dev_rows)[[
        "Model", "Calibration", "Threshold",
        "AUPRC", "Recall", "Precision", "F1", "F2", "ROC-AUC", "MCC",
        "Brier", "LogLoss", "Predicted Fraud Alerts"
    ]]

    anomaly_ablation_test_df = pd.DataFrame(anomaly_test_rows)[[
        "Model", "Calibration", "Threshold",
        "AUPRC", "Recall", "Precision", "F1", "F2", "ROC-AUC", "MCC",
        "Brier", "LogLoss", "Predicted Fraud Alerts"
    ]]

    print("\nAnomaly ablation (development):")
    display(anomaly_ablation_dev_df.round(6))

    print("\nAnomaly ablation (final test):")
    display(anomaly_ablation_test_df.round(6))

    anomaly_ablation_dev_df.to_csv("results/step4_anomaly_ablation_dev.csv", index=False)
    anomaly_ablation_test_df.to_csv("results/step4_anomaly_ablation_test.csv", index=False)

# ---------------------------
# 9) Plots for the selected final model
# ---------------------------
# 9.1 Calibration plot (development)
raw_dev_prob = final_out["raw_dev_prob"]
selected_dev_prob = final_out["chosen_dev_prob"]

frac_pos_raw, mean_pred_raw = calibration_curve(
    y_dev,
    raw_dev_prob,
    n_bins=10,
    strategy="quantile"
)

frac_pos_cal, mean_pred_cal = calibration_curve(
    y_dev,
    selected_dev_prob,
    n_bins=10,
    strategy="quantile"
)

plt.figure(figsize=(8, 6))
plt.plot([0, 1], [0, 1], linestyle="--", label="Perfect calibration")
plt.plot(mean_pred_raw, frac_pos_raw, marker="o", label="Raw")
plt.plot(mean_pred_cal, frac_pos_cal, marker="o", label=f"{final_calibration}")
plt.xlabel("Mean predicted probability")
plt.ylabel("Observed fraud rate")
plt.title(f"Calibration Plot - {final_model_name} (development)")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig("figures/step4_calibration_plot.png", dpi=300, bbox_inches="tight")
plt.show()

# 9.2 Threshold scan plot (development)
threshold_scan_df = final_out["threshold_scan_df"]

plt.figure(figsize=(8, 6))
plt.plot(threshold_scan_df["Threshold"], threshold_scan_df["Recall"], label="Recall")
plt.plot(threshold_scan_df["Threshold"], threshold_scan_df["Precision"], label="Precision")
plt.plot(threshold_scan_df["Threshold"], threshold_scan_df["F2"], label="F2")
plt.axvline(final_threshold, linestyle="--", label=f"Best threshold = {final_threshold:.3f}")
plt.xlabel("Threshold")
plt.ylabel("Score")
plt.title(f"Threshold Scan - {final_model_name} ({final_calibration}, development)")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig("figures/step4_threshold_scan.png", dpi=300, bbox_inches="tight")
plt.show()

# 9.3 Final-test confusion matrix at optimized threshold
final_test_pred = (final_out["chosen_test_prob"] >= final_threshold).astype(int)
cm = confusion_matrix(y_test, final_test_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title(
    f"Final-Test Confusion Matrix - {final_model_name}\n"
    f"({final_calibration}, threshold={final_threshold:.3f})"
)
plt.savefig("figures/step4_test_confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()

# ---------------------------
# 10) Selected final model summary
# ---------------------------
selected_summary_df = pd.DataFrame([{
    "Model": final_model_name,
    "Calibration": final_calibration,
    "Optimized Threshold": final_threshold,
    "Model Selection Rule": MODEL_SELECTION_RULE
}])

selected_summary_df.to_csv("results/step4_selected_model_summary.csv", index=False)

# ---------------------------
# 11) Save bundle for Step 5
# ---------------------------
tp_indices = np.where((final_test_pred == 1) & (np.asarray(y_test) == 1))[0]
fp_indices = np.where((final_test_pred == 1) & (np.asarray(y_test) == 0))[0]
fn_indices = np.where((final_test_pred == 0) & (np.asarray(y_test) == 1))[0]

step4_bundle = {
    "model_selection_rule": MODEL_SELECTION_RULE,
    "final_model_name": final_model_name,
    "final_calibration": final_calibration,
    "final_threshold": final_threshold,

    "step4_calibration_comparison_df": calibration_comparison_df,
    "step4_dev_results_df": step4_dev_results_df,
    "step4_test_results_df": step4_test_results_df,

    "selected_model_ablation_dev_df": selected_model_ablation_dev_df,
    "selected_model_ablation_test_df": selected_model_ablation_test_df,

    "anomaly_ablation_dev_df": anomaly_ablation_dev_df,
    "anomaly_ablation_test_df": anomaly_ablation_test_df,

    "per_model_outputs": per_model_outputs,
    "selected_summary_df": selected_summary_df,

    "final_selected_dev_prob": final_out["chosen_dev_prob"],
    "final_selected_test_prob": final_out["chosen_test_prob"],
    "final_selected_test_pred": final_test_pred,

    "final_test_tp_indices": tp_indices,
    "final_test_fp_indices": fp_indices,
    "final_test_fn_indices": fn_indices
}

joblib.dump(step4_bundle, "models/step4_bundle.joblib")

print("\nSaved:")
print("  results/step4_selected_model_ablation_dev.csv")
print("  results/step4_selected_model_ablation_test.csv")
print("  results/step4_selected_model_summary.csv")
if anomaly_ablation_dev_df is not None:
    print("  results/step4_anomaly_ablation_dev.csv")
    print("  results/step4_anomaly_ablation_test.csv")
print("  figures/step4_calibration_plot.png")
print("  figures/step4_threshold_scan.png")
print("  figures/step4_test_confusion_matrix.png")
print("  models/step4_bundle.joblib")

print("\nStep 4 complete.")

# ============================================================
# STEP 5: SHAP + LIME explainability
#
# What this step does:
# 1) Loads the Step 4 selected final model
# 2) Uses SHAP on the strongest tree-based supervised component
#    (XGBoost baseline) for global and local explanation
# 3) Uses LIME on the final operational model for case-level explanation
# 4) Explains selected final-test cases: TP, FP, and FN
# 5) Saves figures, CSV summaries, HTML reports, and a Step 5 bundle
#
# IMPORTANT:
# - Run this after Step 4
# - Best case: same Colab runtime as Steps 1-4
# - If runtime was restarted, rerun Step 1 first so X_dev/X_test/y_dev/y_test exist
# ============================================================

import warnings
warnings.filterwarnings("ignore")

import os
import json
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

import shap
from lime.lime_tabular import LimeTabularExplainer

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

# ---------------------------
# 0) Folders
# ---------------------------
os.makedirs("results", exist_ok=True)
os.makedirs("figures", exist_ok=True)
os.makedirs("models", exist_ok=True)
os.makedirs("lime_reports", exist_ok=True)

# ---------------------------
# 1) Safety checks and bundle loading
# ---------------------------
required_base_vars = ["RANDOM_STATE"]
missing_base_vars = [v for v in required_base_vars if v not in globals()]
if missing_base_vars:
    raise ValueError(
        f"Run Step 1 first (or restore your runtime). Missing variables: {missing_base_vars}"
    )

if "step3_bundle" not in globals():
    if os.path.exists("models/step3_bundle.joblib"):
        step3_bundle = joblib.load("models/step3_bundle.joblib")
        print("Loaded: models/step3_bundle.joblib")
    else:
        raise ValueError("Step 3 bundle not found. Run Step 3 first.")

if "step4_bundle" not in globals():
    if os.path.exists("models/step4_bundle.joblib"):
        step4_bundle = joblib.load("models/step4_bundle.joblib")
        print("Loaded: models/step4_bundle.joblib")
    else:
        raise ValueError("Step 4 bundle not found. Run Step 4 first.")

required_data_vars = ["X_dev", "X_test", "y_dev", "y_test"]
missing_data_vars = [v for v in required_data_vars if v not in globals()]
if missing_data_vars:
    raise ValueError(
        "Step 5 needs the Step 1 raw split objects still in memory. "
        f"Missing variables: {missing_data_vars}. "
        "Please rerun Step 1 (and keep the same runtime), then run Step 5 again."
    )

X_dev = pd.DataFrame(X_dev).reset_index(drop=True)
X_test = pd.DataFrame(X_test).reset_index(drop=True)
y_dev = pd.Series(y_dev).astype(int).reset_index(drop=True)
y_test = pd.Series(y_test).astype(int).reset_index(drop=True)

# ---------------------------
# 2) Rebuild preprocessor if needed
# ---------------------------
def build_preprocessor_from_step1(X_df, scale_cols):
    other_cols = [c for c in X_df.columns if c not in scale_cols]

    return ColumnTransformer(
        transformers=[
            (
                "scale_selected",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="median")),
                    ("scaler", StandardScaler())
                ]),
                list(scale_cols)
            ),
            (
                "keep_rest",
                "passthrough",
                other_cols
            )
        ],
        remainder="drop",
        verbose_feature_names_out=False
    )

if "preprocessor" not in globals():
    if "scale_cols_later" not in globals():
        raise ValueError(
            "Preprocessor is missing and scale_cols_later is also missing. "
            "Rerun Step 1 first."
        )
    preprocessor = build_preprocessor_from_step1(X_dev, scale_cols_later)
    print("Rebuilt preprocessor from Step 1 variables.")

# ---------------------------
# 3) Rebuild fitted Step 2 baseline models if needed
# ---------------------------
def build_step2_model_specs(scale_pos_weight_value):
    return {
        "Weighted Logistic Regression": LogisticRegression(
            class_weight="balanced",
            max_iter=1000,
            solver="liblinear",
            random_state=RANDOM_STATE
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=200,
            class_weight="balanced_subsample",
            random_state=RANDOM_STATE,
            n_jobs=-1
        ),
        "XGBoost": XGBClassifier(
            n_estimators=200,
            max_depth=5,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="binary:logistic",
            eval_metric="logloss",
            tree_method="hist",
            scale_pos_weight=float(scale_pos_weight_value),
            random_state=RANDOM_STATE,
            n_jobs=-1,
            verbosity=0
        )
    }

def build_step2_pipeline(model):
    return Pipeline([
        ("prep", clone(preprocessor)),
        ("model", clone(model))
    ])

if "fitted_baseline_models" not in globals():
    if "scale_pos_weight" not in globals():
        raise ValueError(
            "fitted_baseline_models is missing and scale_pos_weight is also missing. "
            "Rerun Step 1 + Step 2 in the same runtime, or restore those variables."
        )

    print("Re-fitting Step 2 baseline models on the full development set...")
    fitted_baseline_models = {}
    for model_name, model in build_step2_model_specs(scale_pos_weight).items():
        pipe = build_step2_pipeline(model)
        pipe.fit(X_dev, y_dev)
        fitted_baseline_models[model_name] = pipe
        print(f"  {model_name} ready")

# ---------------------------
# 4) Restore Step 3 objects
# ---------------------------
final_iforest_pipe = step3_bundle["final_iforest_pipe"]
final_stack_supervised = step3_bundle["final_stack_supervised"]
final_stack_hybrid = step3_bundle["final_stack_hybrid"]

# ---------------------------
# 5) Final model selected in Step 4
# ---------------------------
final_model_name = step4_bundle["final_model_name"]
final_calibration = step4_bundle["final_calibration"]
final_threshold = float(step4_bundle["final_threshold"])

per_model_outputs = step4_bundle["per_model_outputs"]
final_model_out = per_model_outputs[final_model_name]
chosen_calibrator = final_model_out["chosen_calibrator"]

print("Step 5 explainability target")
print(f"  Final model      : {final_model_name}")
print(f"  Calibration      : {final_calibration}")
print(f"  Threshold        : {final_threshold:.3f}")

# ---------------------------
# 6) Helper functions
# ---------------------------
def clip_probs(p):
    p = np.asarray(p, dtype=float)
    return np.clip(p, 1e-6, 1 - 1e-6)

def anomaly_score_from_pipeline(pipe, X_df):
    return -pipe.decision_function(X_df)

def to_ordered_dataframe(X_like):
    if isinstance(X_like, pd.DataFrame):
        X_df = X_like.copy()
    else:
        X_df = pd.DataFrame(X_like, columns=X_dev.columns)

    X_df = X_df.loc[:, X_dev.columns]
    return X_df

def get_base_probabilities(X_df):
    X_df = to_ordered_dataframe(X_df)

    lr_prob = fitted_baseline_models["Weighted Logistic Regression"].predict_proba(X_df)[:, 1]
    rf_prob = fitted_baseline_models["Random Forest"].predict_proba(X_df)[:, 1]
    xgb_prob = fitted_baseline_models["XGBoost"].predict_proba(X_df)[:, 1]

    out = pd.DataFrame({
        "lr_prob": lr_prob,
        "rf_prob": rf_prob,
        "xgb_prob": xgb_prob
    })
    return out

def get_raw_final_scores(X_df):
    X_df = to_ordered_dataframe(X_df)
    base_meta = get_base_probabilities(X_df)

    if final_model_name == "Soft Voting (Supervised)":
        raw_prob = base_meta.mean(axis=1).to_numpy()

    elif final_model_name == "Supervised Stacking":
        raw_prob = final_stack_supervised.predict_proba(base_meta)[:, 1]

    elif final_model_name == "Hybrid Stacking + IsolationForest":
        hybrid_meta = base_meta.copy()
        hybrid_meta["iforest_anomaly_score"] = anomaly_score_from_pipeline(final_iforest_pipe, X_df)
        raw_prob = final_stack_hybrid.predict_proba(hybrid_meta)[:, 1]

    else:
        raise ValueError(f"Unknown final model name: {final_model_name}")

    return clip_probs(raw_prob)

def apply_selected_calibration(raw_prob):
    raw_prob = clip_probs(raw_prob)

    if final_calibration == "Raw":
        calibrated = raw_prob

    elif final_calibration == "Platt":
        calibrated = chosen_calibrator.predict_proba(raw_prob.reshape(-1, 1))[:, 1]

    elif final_calibration == "Isotonic":
        calibrated = chosen_calibrator.predict(raw_prob)

    else:
        raise ValueError(f"Unknown calibration method: {final_calibration}")

    return clip_probs(calibrated)

def predict_final_proba(X_like):
    X_df = to_ordered_dataframe(X_like)
    raw_prob = get_raw_final_scores(X_df)
    calibrated_prob = apply_selected_calibration(raw_prob)
    return np.column_stack([1 - calibrated_prob, calibrated_prob])

# ---------------------------
# 7) Sanity check against saved Step 4 test probabilities
# ---------------------------
recomputed_test_prob = predict_final_proba(X_test)[:, 1]
saved_test_prob = np.asarray(step4_bundle["final_selected_test_prob"], dtype=float)
max_abs_diff = float(np.max(np.abs(recomputed_test_prob - saved_test_prob)))

print(f"Max abs difference vs saved Step 4 final-test probabilities: {max_abs_diff:.12f}")

if max_abs_diff > 1e-8:
    print("Warning: recomputed probabilities differ slightly from saved Step 4 probabilities.")
    print("This can happen if some earlier objects were rebuilt. The code still proceeds.")

final_test_prob = saved_test_prob
if "final_selected_test_pred" in step4_bundle:
    final_test_pred = np.asarray(step4_bundle["final_selected_test_pred"]).astype(int)
else:
    final_test_pred = (final_test_prob >= final_threshold).astype(int)

# ---------------------------
# 8) SHAP on strongest tree-based supervised component
#    We use the XGBoost baseline as the explainability anchor.
# ---------------------------
print("\nPart A: SHAP on XGBoost component")

xgb_pipe = fitted_baseline_models["XGBoost"]
xgb_prep = xgb_pipe.named_steps["prep"]
xgb_model = xgb_pipe.named_steps["model"]

rng = np.random.RandomState(RANDOM_STATE)

shap_sample_n = min(2000, len(X_dev))
shap_background_n = min(300, shap_sample_n)

shap_idx = rng.choice(len(X_dev), size=shap_sample_n, replace=False)
X_shap_raw = X_dev.iloc[shap_idx].copy()

X_shap_transformed = xgb_prep.transform(X_shap_raw)
if hasattr(X_shap_transformed, "toarray"):
    X_shap_transformed = X_shap_transformed.toarray()

feature_names_transformed = list(xgb_prep.get_feature_names_out())

background_data = X_shap_transformed[:shap_background_n]

tree_explainer = shap.TreeExplainer(
    xgb_model,
    data=background_data,
    feature_names=feature_names_transformed
)

shap_values = tree_explainer.shap_values(X_shap_transformed)

# Global importance table
mean_abs_shap = np.abs(shap_values).mean(axis=0)
shap_importance_df = pd.DataFrame({
    "Feature": feature_names_transformed,
    "MeanAbsSHAP": mean_abs_shap
}).sort_values(by="MeanAbsSHAP", ascending=False).reset_index(drop=True)

print("\nTop SHAP global features:")
display(shap_importance_df.head(15))

shap_importance_df.to_csv("results/step5_shap_global_importance.csv", index=False)
print("Saved: results/step5_shap_global_importance.csv")

# SHAP beeswarm / summary plot
plt.figure(figsize=(10, 6))
shap.summary_plot(
    shap_values,
    X_shap_transformed,
    feature_names=feature_names_transformed,
    max_display=15,
    show=False
)
plt.title("SHAP Summary Plot - XGBoost Component")
plt.tight_layout()
plt.savefig("figures/step5_shap_summary.png", dpi=300, bbox_inches="tight")
plt.show()

# SHAP bar plot
plt.figure(figsize=(10, 6))
shap.summary_plot(
    shap_values,
    X_shap_transformed,
    feature_names=feature_names_transformed,
    plot_type="bar",
    max_display=15,
    show=False
)
plt.title("SHAP Global Importance (Bar) - XGBoost Component")
plt.tight_layout()
plt.savefig("figures/step5_shap_bar.png", dpi=300, bbox_inches="tight")
plt.show()

# ---------------------------
# 9) Pick representative final-test cases
# ---------------------------
print("\nPart B: Selecting representative final-test cases")

tp_indices = np.asarray(step4_bundle.get("final_test_tp_indices", []), dtype=int)
fp_indices = np.asarray(step4_bundle.get("final_test_fp_indices", []), dtype=int)
fn_indices = np.asarray(step4_bundle.get("final_test_fn_indices", []), dtype=int)

def choose_case(indices, probs, mode="highest"):
    if len(indices) == 0:
        return None

    candidate_probs = probs[indices]

    if mode == "highest":
        chosen_pos = int(np.argmax(candidate_probs))
    elif mode == "lowest":
        chosen_pos = int(np.argmin(candidate_probs))
    else:
        raise ValueError("mode must be 'highest' or 'lowest'")

    return int(indices[chosen_pos])

selected_cases = {
    "TP": choose_case(tp_indices, final_test_prob, mode="highest"),
    "FP": choose_case(fp_indices, final_test_prob, mode="highest"),
    "FN": choose_case(fn_indices, final_test_prob, mode="highest")
}

case_rows = []
for case_type, idx in selected_cases.items():
    if idx is None:
        continue
    case_rows.append({
        "Case Type": case_type,
        "Test Index": int(idx),
        "True Label": int(y_test.iloc[idx]),
        "Predicted Label": int(final_test_pred[idx]),
        "Predicted Fraud Probability": float(final_test_prob[idx])
    })

selected_cases_df = pd.DataFrame(case_rows)
display(selected_cases_df)

selected_cases_df.to_csv("results/step5_selected_cases.csv", index=False)
print("Saved: results/step5_selected_cases.csv")

# ---------------------------
# 10) Local SHAP waterfall plots for selected cases
# ---------------------------
print("\nPart C: Local SHAP waterfall plots")

def save_shap_waterfall(test_idx, case_type):
    X_case_raw = X_test.iloc[[test_idx]].copy()
    X_case_transformed = xgb_prep.transform(X_case_raw)
    if hasattr(X_case_transformed, "toarray"):
        X_case_transformed = X_case_transformed.toarray()

    case_explanation = tree_explainer(X_case_transformed)

    plt.figure(figsize=(9, 6))
    shap.plots.waterfall(case_explanation[0], max_display=12, show=False)
    plt.title(f"SHAP Waterfall - {case_type} Case (test index={test_idx})")
    plt.tight_layout()
    out_path = f"figures/step5_shap_waterfall_{case_type.lower()}.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.show()

    return out_path

shap_local_paths = {}

for case_type, idx in selected_cases.items():
    if idx is None:
        continue
    shap_local_paths[case_type] = save_shap_waterfall(idx, case_type)

# ---------------------------
# 11) LIME on the final operational model
# ---------------------------
print("\nPart D: LIME on the final operational model")

lime_train_n = min(10000, len(X_dev))
lime_idx = rng.choice(len(X_dev), size=lime_train_n, replace=False)

X_lime_train = X_dev.iloc[lime_idx].copy()
y_lime_train = y_dev.iloc[lime_idx].copy()

lime_explainer = LimeTabularExplainer(
    training_data=X_lime_train.values,
    training_labels=y_lime_train.values,
    feature_names=list(X_dev.columns),
    class_names=["Legitimate", "Fraud"],
    mode="classification",
    discretize_continuous=True,
    random_state=RANDOM_STATE
)

def save_lime_outputs(test_idx, case_type, num_features=10):
    instance = X_test.iloc[test_idx].values

    explanation = lime_explainer.explain_instance(
        data_row=instance,
        predict_fn=predict_final_proba,
        labels=(1,),
        num_features=num_features
    )

    lime_weights = explanation.as_list(label=1)
    lime_df = pd.DataFrame(lime_weights, columns=["Feature", "Weight"])
    lime_df["Case Type"] = case_type
    lime_df["Test Index"] = int(test_idx)
    lime_df["True Label"] = int(y_test.iloc[test_idx])
    lime_df["Predicted Label"] = int(final_test_pred[test_idx])
    lime_df["Predicted Fraud Probability"] = float(final_test_prob[test_idx])

    csv_path = f"results/step5_lime_{case_type.lower()}_weights.csv"
    html_path = f"lime_reports/step5_lime_{case_type.lower()}.html"
    png_path = f"figures/step5_lime_{case_type.lower()}.png"

    lime_df.to_csv(csv_path, index=False)

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(explanation.as_html())

    plot_df = lime_df[["Feature", "Weight"]].sort_values(by="Weight", ascending=True)
    plt.figure(figsize=(9, 5))
    plt.barh(plot_df["Feature"], plot_df["Weight"])
    plt.xlabel("LIME weight toward fraud class")
    plt.title(f"LIME Explanation - {case_type} Case (test index={test_idx})")
    plt.tight_layout()
    plt.savefig(png_path, dpi=300, bbox_inches="tight")
    plt.show()

    return lime_df, csv_path, html_path, png_path

lime_frames = []
lime_outputs = {}

for case_type, idx in selected_cases.items():
    if idx is None:
        continue

    lime_df, csv_path, html_path, png_path = save_lime_outputs(idx, case_type)
    lime_frames.append(lime_df)
    lime_outputs[case_type] = {
        "csv_path": csv_path,
        "html_path": html_path,
        "png_path": png_path
    }

if len(lime_frames) > 0:
    all_lime_df = pd.concat(lime_frames, ignore_index=True)
else:
    all_lime_df = pd.DataFrame(columns=[
        "Feature", "Weight", "Case Type", "Test Index",
        "True Label", "Predicted Label", "Predicted Fraud Probability"
    ])

all_lime_df.to_csv("results/step5_lime_case_summaries.csv", index=False)
print("Saved: results/step5_lime_case_summaries.csv")

# ---------------------------
# 12) Compact explainability summary table
# ---------------------------
summary_rows = [{
    "Final Model": final_model_name,
    "Calibration": final_calibration,
    "Threshold": final_threshold,
    "SHAP Anchor Component": "XGBoost baseline",
    "Selected TP Index": selected_cases.get("TP"),
    "Selected FP Index": selected_cases.get("FP"),
    "Selected FN Index": selected_cases.get("FN"),
    "Selected TP Probability": None if selected_cases.get("TP") is None else float(final_test_prob[selected_cases["TP"]]),
    "Selected FP Probability": None if selected_cases.get("FP") is None else float(final_test_prob[selected_cases["FP"]]),
    "Selected FN Probability": None if selected_cases.get("FN") is None else float(final_test_prob[selected_cases["FN"]])
}]

step5_explainability_summary_df = pd.DataFrame(summary_rows)
display(step5_explainability_summary_df)

step5_explainability_summary_df.to_csv("results/step5_explainability_summary.csv", index=False)
print("Saved: results/step5_explainability_summary.csv")

# ---------------------------
# 13) Save bundle for final paper writing
# ---------------------------
step5_bundle = {
    "final_model_name": final_model_name,
    "final_calibration": final_calibration,
    "final_threshold": final_threshold,

    "selected_cases_df": selected_cases_df,
    "step5_explainability_summary_df": step5_explainability_summary_df,
    "shap_importance_df": shap_importance_df,
    "all_lime_df": all_lime_df,

    "shap_local_paths": shap_local_paths,
    "lime_outputs": lime_outputs
}

joblib.dump(step5_bundle, "models/step5_bundle.joblib")
print("Saved: models/step5_bundle.joblib")

print("\nSaved files from Step 5:")
print("  results/step5_shap_global_importance.csv")
print("  results/step5_selected_cases.csv")
print("  results/step5_lime_case_summaries.csv")
print("  results/step5_explainability_summary.csv")
print("  figures/step5_shap_summary.png")
print("  figures/step5_shap_bar.png")
for case_type, path in shap_local_paths.items():
    print(f"  {path}")
for case_type, paths in lime_outputs.items():
    print(f"  {paths['csv_path']}")
    print(f"  {paths['html_path']}")
    print(f"  {paths['png_path']}")
print("  models/step5_bundle.joblib")

print("\nStep 5 complete.")

import shutil
from google.colab import files

# Create a zip of the entire 'content' directory
# (Excluding the hidden .config folder to keep it clean)
shutil.make_archive('all_colab_files', 'zip', '/content')

# Download
files.download('all_colab_files.zip')